import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, Button } from "react-bootstrap";
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import { useRouter } from "next/router";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar"; 


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Web Banking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.main}>
          <div className={styles.top} style={{ fontSize: "30px" }}>
            <div>Webbank</div>
          </div>
        </div>
        <div className={styles.card}>
          <Card style={{ width: "30rem" }}>
            <Card.Body>
              <Card.Title style={{ textAlign: "center" }}>Login</Card.Title>
              <div>
                <Form.Label htmlFor="basic-url">Username</Form.Label>
                <InputGroup className="mb-3">
                  <Form.Control
                    id="basic-url"
                    aria-describedby="basic-addon3"
                  />
                </InputGroup>
                <Form.Label htmlFor="basic-url">Password</Form.Label>
                <InputGroup className="mb-4">
                  <Form.Control
                    id="basic-url"
                    aria-describedby="basic-addon3"
                  />
                </InputGroup>
              </div>
              <Button href="/menu" variant="success" style={{ width: "100%" }}>
                Confirm
              </Button>
              <div
                style={{
                  textAlign: "right",
                  paddingTop: "10px",
                  cursor: "pointer",
                }}
                onClick={() => {
                  router.push("/register");
                }}
              >
                Register
              </div>
            </Card.Body>
          </Card>
        </div>
        <div className={styles.footer}>
          <div style={{ paddingLeft: "100px", paddingTop: "50px" }}>
            <div style={{ paddingBottom: "10px" }}>Facebook: hkm@Webbank.com</div>
            <div>line: hkm@Webbank.com</div>
          </div>
          <div style={{ paddingRight: "100px", paddingTop: "50px" }}>
            Contact: 09-9999-999
          </div>
        </div>
      </main>
    </div>
  );
}