import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, Button } from "react-bootstrap";
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import { useRouter } from "next/router";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar"; 
import Dropdown from 'react-bootstrap/Dropdown';
import DropdownButton from 'react-bootstrap/DropdownButton';


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Web Banking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.menu}>
          <div className={styles.top} style={{ fontSize: "30px" }}>
            <div>Webbank</div>
          </div>
          <div style={{justifyItem:"right"}}>
          <DropdownButton
      align="end"
      title="Username"
      id="dropdown-menu-align-end"
      variant="success"
    >
      <Dropdown.Item eventKey="1"
      style={{
        cursor: "pointer"
      }}
      onClick={() => {
        router.push("/menu");
      }} >Menu</Dropdown.Item>
      
      <Dropdown.Divider />
      <Dropdown.Item eventKey="4"
      style={{
        cursor: "pointer"
      }}
      onClick={() => {
        router.push("/");
      }} 
      >Sign Out</Dropdown.Item>
      </DropdownButton>
            </div>
         </div>
        <div className={styles.card}>
          <Card style={{ width: "30rem" }}>
            <Card.Body>
              <Card.Title style={{ textAlign: "center" }}>โอนเงิน</Card.Title>
              <div>
                <Form.Label htmlFor="basic-url">เลขบัญชีผู้รับ</Form.Label>
                <InputGroup className="mb-3">
                  <Form.Control
                    id="basic-url"
                    aria-describedby="basic-addon3"
                  />
                </InputGroup>
                <Form.Label htmlFor="basic-url">จำนวนเงินที่ต้องการโอน</Form.Label>
                <InputGroup className="mb-3">
                  <Form.Control
                    id="basic-url"
                    aria-describedby="basic-addon3"
                  />
                </InputGroup>
            
              </div>
              <Button href="/menu" variant="success" style={{ width: "100%" }}>
                Confirm
              </Button>
            </Card.Body>
          </Card>
        </div>
    </main>
    </div>
  );
}